import React, { useState, useEffect } from "react";
import { GoogleGenAI } from "@google/genai";

const PG={HOME:"home",TRAINING:"training",WATCH:"watch",BOOK:"book",ABOUT:"about",LIBRARY:"library",FOUNDATION:"foundation",GIVE:"give",PRIVACY:"privacy",TERMS:"terms",DISCLAIMER:"disclaimer"};
const FN=[PG.TRAINING,PG.WATCH,PG.BOOK];

const GS=()=>(<style>{`
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap');
:root{--bg:#0a0a0a;--bg2:#111;--gold:#c9a84c;--gold-l:#e4cc7a;--gold-d:#a8872e;--cream:#f5f0e8;--cream-m:#d4cfc5;--dim:#7a756b;--muted:#b0aa9e;--serif:'Playfair Display',Georgia,serif;--body:'Libre Baskerville',Georgia,serif;--accent:'Cormorant Garamond',Georgia,serif}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{background:var(--bg);color:var(--cream);font-family:var(--body);-webkit-font-smoothing:antialiased;font-size:20px}::selection{background:rgba(201,168,76,.3);color:var(--cream)}
@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.fade-in{opacity:0;animation:fadeUp .7s ease forwards}.d1{animation-delay:.2s}.d2{animation-delay:.4s}.d3{animation-delay:.6s}.d4{animation-delay:.8s}@keyframes spin{to{transform:rotate(360deg)}}
`}</style>);

// ── Atoms ──
const Btn=({children,onClick,large,href})=>{const s={fontFamily:"var(--accent)",fontSize:large?"1.25rem":"1.1rem",fontWeight:600,letterSpacing:".16em",textTransform:"uppercase",color:"var(--bg)",background:"linear-gradient(135deg,var(--gold-l),var(--gold),var(--gold-d))",padding:large?"1.15rem 3.2rem":".75rem 1.8rem",border:"none",cursor:"pointer",transition:"all .35s",display:"inline-block",textDecoration:"none"};return href?<a href={href} target="_blank" rel="noopener noreferrer" style={s}>{children}</a>:<button onClick={onClick} style={s}>{children}</button>};
const SL=({children})=>(<div style={{fontFamily:"var(--accent)",fontSize:"1.05rem",fontWeight:600,letterSpacing:".22em",textTransform:"uppercase",color:"var(--gold-d)",marginBottom:"2rem"}}>{children}</div>);
const Hd=({children,sz="clamp(1.8rem,3.5vw,2.6rem)"})=>(<h2 style={{fontFamily:"var(--serif)",fontSize:sz,fontWeight:700,color:"var(--cream)",lineHeight:1.3,marginBottom:"1.5rem"}}>{children}</h2>);
const Bd=({children,c})=>(<p style={{fontSize:"1.35rem",color:"var(--muted)",marginBottom:"1.5rem",lineHeight:1.75,textAlign:c?"center":"left"}}>{children}</p>);
const CB=({t,d})=>(<div style={{borderLeft:"2px solid var(--gold-d)",padding:"1.5rem 2rem",margin:"1.5rem 0",background:"rgba(201,168,76,.03)"}}><h3 style={{fontFamily:"var(--serif)",fontSize:"1.4rem",color:"var(--gold-l)",marginBottom:".6rem"}}>{t}</h3><p style={{fontSize:"1.2rem",color:"var(--cream-m)",lineHeight:1.65,margin:0}}>{d}</p></div>);
const FI=({t})=>(<div style={{display:"flex",gap:"1rem",padding:".9rem 0",borderBottom:"1px solid rgba(201,168,76,.06)"}}><span style={{color:"var(--gold)",fontSize:"1.2rem",flexShrink:0}}>◆</span><span style={{fontFamily:"var(--accent)",fontSize:"1.2rem",color:"var(--cream-m)",lineHeight:1.55}}>{t}</span></div>);
const RI=({c})=>(<div style={{display:"flex",alignItems:"baseline",gap:"1rem",padding:".75rem 0",borderBottom:"1px solid rgba(201,168,76,.08)",fontSize:"1.25rem"}}><span style={{color:"var(--gold)"}}>✓</span><span style={{textDecoration:"line-through",color:"var(--dim)"}}>{c}</span><span style={{color:"var(--gold)",fontWeight:700,fontSize:"1.1rem",marginLeft:"auto"}}>RESOLVED</span></div>);
const SI=({t})=>(<div style={{background:"var(--bg)",padding:"1.3rem 1.6rem",fontFamily:"var(--accent)",fontSize:"1.25rem",color:"var(--cream-m)",display:"flex",alignItems:"center",gap:".8rem"}}><span style={{color:"var(--gold-d)"}}>—</span>{t}</div>);
const Sec=({children,bg,pad="5rem 0"})=>(<section style={{padding:pad,background:bg||"transparent",borderTop:bg?"1px solid rgba(201,168,76,.1)":"none",borderBottom:bg?"1px solid rgba(201,168,76,.1)":"none"}}><div style={{maxWidth:820,margin:"0 auto",padding:"0 1.5rem"}}>{children}</div></section>);
const VT=({id,h,name})=>(<div style={{background:"var(--bg2)",border:"1px solid rgba(201,168,76,.1)",overflow:"hidden"}}><div style={{position:"relative",width:"100%",paddingBottom:"177.78%"}}><iframe src={`https://player.vimeo.com/video/${id}?h=${h}&badge=0&autopause=0`} style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",border:"none"}} allow="autoplay; fullscreen" allowFullScreen title={name}/></div><div style={{padding:".8rem 1rem",textAlign:"center"}}><span style={{fontFamily:"var(--accent)",fontSize:"1.1rem",color:"var(--gold-d)"}}>{name}</span></div></div>);
const TR=({items,cols=3})=>(<><style>{`@media(max-width:768px){.kf-tr{grid-template-columns:1fr!important}}`}</style><div className="kf-tr" style={{display:"grid",gridTemplateColumns:`repeat(${cols},1fr)`,gap:"1rem"}}>{items.map(i=><VT key={i.name+i.id} {...i}/>)}</div></>);
const BC=({img,title,price,amz})=>(<div style={{background:"var(--bg2)",border:"1px solid rgba(201,168,76,.08)",padding:"1rem",display:"flex",flexDirection:"column",alignItems:"center",textAlign:"center"}}><img src={img} alt={title} style={{width:"100%",maxWidth:170,height:"auto",border:"1px solid rgba(201,168,76,.12)",marginBottom:"1rem"}}/><h3 style={{fontFamily:"var(--serif)",fontSize:"1.1rem",fontWeight:700,color:"var(--cream)",lineHeight:1.3,marginBottom:".5rem",minHeight:"2.6rem"}}>{title}</h3><span style={{fontFamily:"var(--serif)",fontSize:"1.2rem",fontWeight:700,color:"var(--gold)",marginBottom:".8rem"}}>{price}</span><Btn href={amz}>Amazon</Btn></div>);
const Bridge=()=>(<p style={{fontFamily:"var(--accent)",fontSize:"1.05rem",color:"var(--dim)",marginBottom:"2rem",fontStyle:"italic"}}>Some testimonials reference my former name, Matthew David Hurtado.</p>);

// ── Nav ──
const Nav=({pg,sp})=>{const f=FN.includes(pg);const[sc,setSc]=useState(false);const[mo,setMo]=useState(false);useEffect(()=>{const h=()=>setSc(window.scrollY>40);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h)},[]);
const navBg=sc?"rgba(10,10,10,.95)":"rgba(10,10,10,.8)";
return(<>
<nav style={{position:"fixed",top:0,left:0,right:0,zIndex:100,display:"flex",justifyContent:"space-between",alignItems:"center",padding:"1rem 1.5rem",background:navBg,backdropFilter:"blur(12px)",borderBottom:"1px solid rgba(201,168,76,.12)"}}>
  <span onClick={()=>{sp(PG.HOME);setMo(false)}} style={{fontFamily:"var(--accent)",fontSize:"1.4rem",fontWeight:600,color:"var(--cream)",letterSpacing:".08em",cursor:"pointer"}}>Kingley Foundation</span>
  <div style={{display:"flex",alignItems:"center",gap:"1rem"}}>
    <div className="kf-desktop-links" style={{display:"flex",gap:"1.8rem",alignItems:"center"}}>
      {!f&&<>{[["About",PG.ABOUT],["Library",PG.LIBRARY],["Foundation",PG.FOUNDATION]].map(([l,p])=>(<span key={p} onClick={()=>sp(p)} style={{fontFamily:"var(--accent)",fontSize:"1.15rem",color:pg===p?"var(--cream)":"var(--muted)",cursor:"pointer"}}>{l}</span>))}<span onClick={()=>sp(PG.TRAINING)} style={{fontFamily:"var(--accent)",fontSize:"1.1rem",color:"var(--gold-d)",cursor:"pointer"}}>Free Training</span></>}
    </div>
    <button onClick={()=>sp(PG.GIVE)} style={{fontFamily:"var(--accent)",fontSize:"1.05rem",fontWeight:700,letterSpacing:".18em",textTransform:"uppercase",color:"var(--bg)",background:"var(--gold)",padding:".6rem 1.6rem",border:"none",cursor:"pointer"}}>GIVE</button>
    <button onClick={()=>setMo(!mo)} className="kf-hamburger" style={{display:"none",flexDirection:"column",justifyContent:"center",alignItems:"center",gap:"5px",background:"none",border:"none",cursor:"pointer",padding:"4px",width:36,height:36}}>
      <span style={{display:"block",width:22,height:2,background:mo?"var(--gold)":"var(--cream)",transition:"all .25s",transform:mo?"rotate(45deg) translate(5px,5px)":"none"}}/>
      <span style={{display:"block",width:22,height:2,background:mo?"var(--gold)":"var(--cream)",transition:"all .25s",opacity:mo?0:1}}/>
      <span style={{display:"block",width:22,height:2,background:mo?"var(--gold)":"var(--cream)",transition:"all .25s",transform:mo?"rotate(-45deg) translate(5px,-5px)":"none"}}/>
    </button>
  </div>
</nav>
{mo&&<div style={{position:"fixed",top:"60px",left:0,right:0,zIndex:99,background:"rgba(10,10,10,.97)",borderBottom:"1px solid rgba(201,168,76,.15)",display:"flex",flexDirection:"column",padding:"1.5rem 2rem",gap:"0"}}>
  {!f&&<>{[["About",PG.ABOUT],["Library",PG.LIBRARY],["Foundation",PG.FOUNDATION]].map(([l,p])=>(<span key={p} onClick={()=>{sp(p);setMo(false)}} style={{fontFamily:"var(--accent)",fontSize:"1.2rem",color:pg===p?"var(--cream)":"var(--muted)",cursor:"pointer",padding:".75rem 0",borderBottom:"1px solid rgba(201,168,76,.08)",display:"block"}}>{l}</span>))}<span onClick={()=>{sp(PG.TRAINING);setMo(false)}} style={{fontFamily:"var(--accent)",fontSize:"1.15rem",color:"var(--gold-d)",cursor:"pointer",padding:".75rem 0",display:"block"}}>Free Training</span></>}
</div>}
<style>{`@media(max-width:768px){.kf-desktop-links{display:none!important}.kf-hamburger{display:flex!important}}`}</style>
</>);};

// ═══════════════════════════════════════════
// HOME
// ═══════════════════════════════════════════
const Home=({sp})=>(<>
<section style={{minHeight:"100vh",display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",textAlign:"center",padding:"8rem 1.5rem 5rem",position:"relative"}}><div style={{position:"absolute",inset:0,background:"radial-gradient(ellipse 60% 40% at 50% 20%,rgba(201,168,76,.06) 0%,transparent 70%)",pointerEvents:"none"}}/><div className="fade-in d1" style={{fontFamily:"var(--accent)",fontSize:"1.05rem",fontWeight:600,letterSpacing:".22em",textTransform:"uppercase",color:"var(--gold)",marginBottom:"2.5rem"}}><span style={{borderTop:"1px solid var(--gold-d)",borderBottom:"1px solid var(--gold-d)",padding:".5rem 0",display:"inline-block"}}>Your doctor found nothing. Your body disagrees.</span></div><h1 className="fade-in d2" style={{fontFamily:"var(--serif)",fontSize:"clamp(2.6rem,5.5vw,4.8rem)",fontWeight:900,lineHeight:1.1,color:"var(--cream)",maxWidth:900,marginBottom:"2rem"}}>"Everything Came Back <em style={{color:"var(--gold)",fontStyle:"italic"}}>Normal.</em>"</h1><p className="fade-in d3" style={{fontSize:"clamp(1.15rem,2vw,1.35rem)",color:"var(--muted)",maxWidth:640,lineHeight:1.8,marginBottom:"2.5rem"}}>I had 11 unexplained conditions. Every test was clear. Every specialist shrugged. Then I found the one thing they never thought to look for — and eliminated every symptom. Not managed. <strong style={{color:"var(--cream)"}}>Eliminated.</strong></p><div className="fade-in d4" style={{display:"flex",flexDirection:"column",alignItems:"center",gap:"1rem"}}><Btn large onClick={()=>sp(PG.TRAINING)}>Watch the Free Training</Btn><span style={{fontFamily:"var(--accent)",fontSize:"1.05rem",color:"var(--dim)"}}>30-min training + free book + free 15-min session</span></div></section>
<Sec><SL>If this is your life, keep reading</SL><Hd>You've been to the doctor. The bloodwork. The MRIs. The specialists. Same thing every time.</Hd><Bd>"We can't find anything wrong."</Bd><Bd>But the symptoms are still here. And the worst part isn't the pain — it's the feeling that <strong style={{color:"var(--cream)"}}>no one believes you.</strong></Bd><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"1px",margin:"2.5rem 0",background:"rgba(201,168,76,.1)"}}>{["Chronic fatigue no rest can touch","Numbness or tingling, no cause","Panic attacks out of nowhere","Brain fog","IBS or stomach issues","Body twitching","Anxiety becoming agoraphobia","Widespread pain, no diagnosis","Insomnia despite exhaustion",'"Chronic Lyme" after antibiotics'].map((s,i)=><SI key={i} t={s}/>)}</div></Sec>
<Sec bg="var(--bg2)"><SL>What they missed</SL><Hd>Every symptom is a biological program — purposeful, specific, traceable to an exact moment.</Hd><CB t="The Off Note" d="Every conflict is sustained by a thinking error. Correct it, the biological program collapses."/><CB t="The Tracks" d="Your brain recorded everything when the shock occurred. Anything that rhymes with it reactivates the program."/><CB t="The Two Phases" d="You feel worst when life gets better — repair mode. The fatigue, inflammation, flare-ups? That's healing."/></Sec>
<Sec><div style={{textAlign:"center"}}><SL>My story. My proof.</SL><Hd>I carried 11 conditions. Eliminated every one.</Hd></div><div style={{maxWidth:560,margin:"0 auto 2rem"}}>{["Chronic Fatigue","Right Foot/Leg Numbness","Body Twitching","Panic Attacks","Agoraphobia","OCD","Bulimia (5 years)","Depression","High Blood Pressure","Chronic Lyme Symptoms","cPTSD"].map((c,i)=><RI key={i} c={c}/>)}</div></Sec>
<Sec bg="var(--bg2)"><SL>What others are saying</SL><Bridge/><TR items={[{id:"1181871159",h:"eb614a9a20",name:"Vernita"},{id:"1181871713",h:"34b14d1127",name:"Sylvia"},{id:"1181872201",h:"1d3bdb7e07",name:"Matt"}]}/></Sec>
<Sec><div style={{textAlign:"center"}}><SL>Free training</SL><Hd sz="clamp(2rem,4vw,3rem)">Watch the Training. Get the Book. Book Your <em style={{color:"var(--gold)",fontStyle:"italic"}}>Free</em> Session.</Hd></div><div style={{maxWidth:580,margin:"2rem auto 0",padding:"2.5rem 2rem",background:"rgba(201,168,76,.03)",border:"1px solid rgba(201,168,76,.12)",textAlign:"center"}}><h3 style={{fontFamily:"var(--serif)",fontSize:"1.5rem",fontWeight:700,color:"var(--cream)",marginBottom:"1.2rem"}}>All free:</h3><div style={{textAlign:"left",marginBottom:"1.5rem"}}><FI t="30-minute training — the complete framework"/><FI t="The book — instant download — 'Everything Came Back Normal'"/><FI t="Free 15-minute session — your symptoms mapped, zero cost"/></div><Btn large onClick={()=>sp(PG.TRAINING)}>Get Instant Access</Btn></div></Sec>
<section style={{padding:"4rem 1.5rem",textAlign:"center",maxWidth:680,margin:"0 auto"}}><img src="https://i.imgur.com/M01AjHR.jpg" alt="Malcolm Kingley" style={{width:"100%",maxWidth:500,margin:"0 auto 2rem",display:"block",border:"1px solid rgba(201,168,76,.1)"}}/><p style={{fontFamily:"var(--serif)",fontSize:"clamp(1.3rem,2.5vw,1.65rem)",fontStyle:"italic",color:"var(--cream)",lineHeight:1.55}}>"Find the off note. Correct the thought. Watch the body follow."</p><p style={{fontFamily:"var(--accent)",fontSize:"1.1rem",color:"var(--gold-d)",marginTop:"1.5rem"}}>— Malcolm Kingley</p></section>
</>);

// ═══════════════════════════════════════════
// TRAINING + WATCH + BOOK (kept compact)
// ═══════════════════════════════════════════
const Training=({sp})=>{const[n,sn]=useState("");const[e,se]=useState("");const[sending,setSending]=useState(false);const I={width:"100%",padding:".9rem 1.1rem",marginBottom:".9rem",background:"var(--bg)",border:"1px solid rgba(201,168,76,.15)",color:"var(--cream)",fontFamily:"var(--accent)",fontSize:"1.1rem",outline:"none"};const submit=async()=>{if(!e.trim())return;setSending(true);try{await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/brevo-subscribe`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`},body:JSON.stringify({email:e.trim(),firstName:n.trim()})})}catch(err){console.log("Brevo:",err)}finally{setSending(false);sp(PG.WATCH)}};return(<div style={{maxWidth:960,margin:"0 auto",padding:"7rem 1.5rem 3rem"}}><div style={{textAlign:"center",marginBottom:"2.5rem"}} className="fade-in d1"><span style={{fontFamily:"var(--accent)",fontSize:"1rem",fontWeight:600,letterSpacing:".22em",textTransform:"uppercase",color:"var(--gold)",border:"1px solid rgba(201,168,76,.25)",padding:".5rem 1.5rem",background:"rgba(201,168,76,.04)",display:"inline-block",marginBottom:"1.5rem"}}>FREE TRAINING</span><h1 style={{fontFamily:"var(--serif)",fontSize:"clamp(1.6rem,3.5vw,2.4rem)",fontWeight:700,color:"var(--cream)",lineHeight:1.25}}>Why Your Doctor Can't Find What's Wrong<br/><em style={{color:"var(--gold)",fontStyle:"italic"}}>And What's Actually Causing Your Symptoms</em></h1></div><div style={{maxWidth:500,margin:"0 auto"}} className="fade-in d2"><div style={{marginBottom:"1.5rem"}}><FI t="Why your tests keep coming back 'normal'"/><FI t="The hidden logic behind chronic fatigue, numbness, panic"/><FI t="The single thinking error behind every unexplained symptom"/></div><div style={{background:"var(--bg2)",border:"1px solid rgba(201,168,76,.12)",padding:"2rem",textAlign:"center"}}><input value={n} onChange={x=>sn(x.target.value)} placeholder="First Name" style={I}/><input value={e} onChange={x=>se(x.target.value)} placeholder="Email" type="email" style={I}/><Btn large onClick={submit}>{sending?"Sending...":"Watch the Free Training"}</Btn></div></div><div style={{marginTop:"3rem"}}><SL>Others who watched</SL><Bridge/><TR items={[{id:"1181881749",h:"a2dfd68472",name:"Eric"},{id:"1181882145",h:"d8b059f862",name:"Edmond"},{id:"1181882369",h:"9f710c8590",name:"Sabrina"}]}/></div></div>)};

const Watch=({sp})=>(<div style={{maxWidth:960,margin:"0 auto",padding:"6rem 1.5rem 3rem"}}><div style={{textAlign:"center",marginBottom:"2rem"}} className="fade-in d1"><span style={{fontFamily:"var(--accent)",fontSize:"1rem",fontWeight:600,letterSpacing:".22em",textTransform:"uppercase",color:"var(--gold)",border:"1px solid rgba(201,168,76,.25)",padding:".5rem 1.5rem",background:"rgba(201,168,76,.04)",display:"inline-block"}}>PRIVATE TRAINING</span><h1 style={{fontFamily:"var(--serif)",fontSize:"clamp(1.5rem,3.2vw,2.2rem)",fontWeight:700,color:"var(--cream)",lineHeight:1.25,marginTop:"1.5rem"}}>Why Your Doctor Can't Find What's Wrong</h1></div><div className="fade-in d2" style={{border:"1px solid rgba(201,168,76,.15)",background:"#000"}}><div style={{position:"relative",width:"100%",paddingBottom:"56.25%"}}><iframe src="https://player.vimeo.com/video/1181669158?h=be69ff8bd7&badge=0&autopause=0" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",border:"none"}} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/></div></div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:"1.5rem",padding:"1.4rem 2rem",background:"var(--bg2)",border:"1px solid rgba(201,168,76,.12)",borderTop:"2px solid var(--gold-d)",flexWrap:"wrap"}}><img src="https://i.imgur.com/i1DT8Sg.jpg" alt="Book" style={{width:55,border:"1px solid rgba(201,168,76,.15)"}}/><div><div style={{fontFamily:"var(--serif)",fontSize:"1.1rem",fontWeight:700,color:"var(--cream)"}}>"Everything Came Back Normal" — Free Download</div></div><Btn>Download Free Book</Btn></div><div style={{background:"var(--bg2)",border:"1px solid rgba(201,168,76,.12)",borderTop:"none",padding:"2.5rem 2rem",textAlign:"center",marginBottom:"2.5rem"}}><h2 style={{fontFamily:"var(--serif)",fontSize:"clamp(1.4rem,2.8vw,1.9rem)",fontWeight:700,color:"var(--cream)",marginBottom:".6rem"}}>Book Your <em style={{color:"var(--gold)",fontStyle:"italic"}}>Free</em> 15-Minute Session</h2><Btn large onClick={()=>sp(PG.BOOK)}>Book Your Session Now</Btn></div><SL>More from our community</SL><Bridge/><TR cols={2} items={[{id:"1181873462",h:"e3f0ffe9c6",name:"Roni"},{id:"1181874340",h:"a7dcb589e2",name:"Dr. Lee"}]}/></div>);

const Book=()=>(<div style={{maxWidth:960,margin:"0 auto",padding:"7rem 1.5rem 3rem"}}><style>{`@media(max-width:768px){.kf-book-grid{grid-template-columns:1fr!important}}`}</style><div style={{textAlign:"center",marginBottom:"2rem"}} className="fade-in d1"><h1 style={{fontFamily:"var(--serif)",fontSize:"clamp(1.8rem,4vw,2.8rem)",fontWeight:900,color:"var(--cream)",marginBottom:".8rem"}}>15 Minutes With Malcolm. <em style={{color:"var(--gold)",fontStyle:"italic"}}>Zero Cost.</em></h1></div><div className="kf-book-grid fade-in d2" style={{display:"grid",gridTemplateColumns:"280px 1fr",gap:"2rem",alignItems:"start"}}><div><div style={{padding:"2rem",background:"var(--bg2)",border:"1px solid rgba(201,168,76,.1)",marginBottom:"1rem"}}><h3 style={{fontFamily:"var(--serif)",fontSize:"1.2rem",fontWeight:700,color:"var(--cream)",marginBottom:"1rem"}}>Your session:</h3><FI t="Symptoms mapped"/><FI t="Off note identified"/><FI t="Path forward clear"/></div><VT id="1181875859" h="644694f38f" name="Liz"/></div><div style={{position:"relative"}}><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",background:"var(--bg2)",border:"1px solid rgba(201,168,76,.1)",pointerEvents:"none",zIndex:0}}><div style={{width:36,height:36,border:"3px solid rgba(201,168,76,.2)",borderTopColor:"var(--gold)",borderRadius:"50%",animation:"spin 1s linear infinite",marginBottom:"1rem"}}/><p style={{fontFamily:"var(--accent)",color:"var(--gold-d)",fontSize:".95rem",letterSpacing:".1em"}}>Loading calendar…</p></div><iframe src="https://calendly.com/ministerofallowing/15min?embed_domain=malcomkingley.org&embed_type=Inline" width="100%" height="700" frameBorder="0" title="Schedule a session" style={{border:"none",minWidth:320,position:"relative",zIndex:1}} onLoad={e=>e.target.previousSibling.style.display="none"}/></div></div></div>);

// ═══════════════════════════════════════════
// ABOUT
// ═══════════════════════════════════════════
const About=({sp})=>(<><Sec pad="8rem 0 4rem"><SL>About</SL><Hd sz="clamp(2.2rem,4.5vw,3.2rem)">Malcolm Kingley</Hd><p style={{fontFamily:"var(--accent)",fontSize:"1.15rem",color:"var(--gold-d)",marginBottom:"2rem"}}>Founder, Kingley Foundation</p><img src="https://i.imgur.com/M01AjHR.jpg" alt="Malcolm" style={{width:"100%",maxWidth:500,border:"1px solid rgba(201,168,76,.12)",marginBottom:"2rem"}}/><Bd>I carried 11 unexplained conditions for over a decade. Every specialist found nothing. Then I discovered a framework that mapped every symptom to an exact emotional conflict — and a method for correcting the thinking error at its root. I eliminated every condition. Then I built the technology and the school so others could do the same.</Bd></Sec><Sec bg="var(--bg2)"><SL>The Timeline</SL><div style={{borderLeft:"2px solid var(--gold-d)",paddingLeft:"2rem",marginLeft:"1rem"}}>{[["Age 2–12","Early conflicts. Accident, father leaving, near-drowning."],["Age 19","Bulimia begins. 5-year pattern."],["Age 30","Agoraphobia, OCD, chronic fatigue."],["Age 44","11 conditions peak. Medical system exhausted."],["Discovery","German New Medicine. Every symptom mapped."],["Resolution","Spiritual correction. Every symptom eliminated."],["Creation","She-Wolf AI. Operator School."],["Launch","Kingley Foundation. 508(c)(1)(A)."],["Today","12 books. Minister. Operator. 126K+."]].map(([l,d],i)=>(<div key={i} style={{marginBottom:"2rem",position:"relative"}}><div style={{position:"absolute",left:"-2.6rem",top:".35rem",width:11,height:11,borderRadius:"50%",background:"var(--gold-d)"}}/><div style={{fontFamily:"var(--serif)",fontSize:"1.1rem",fontWeight:700,color:"var(--gold-l)",marginBottom:".3rem"}}>{l}</div><div style={{fontFamily:"var(--accent)",fontSize:"1.1rem",color:"var(--cream-m)",lineHeight:1.55}}>{d}</div></div>))}</div></Sec><Sec><SL>What people say</SL><Bridge/><TR cols={2} items={[{id:"1181878262",h:"2131f58a37",name:"Peter"},{id:"1181877843",h:"de992d0a8e",name:"Eduardo"},{id:"1181879660",h:"d61ff65a08",name:"Kimona"},{id:"1181880037",h:"6c618be918",name:"Cherie"}]}/><div style={{textAlign:"center",marginTop:"3rem"}}><Btn large onClick={()=>sp(PG.BOOK)}>Start With a Free 15-Minute Session</Btn></div></Sec></>);

// ═══════════════════════════════════════════
// LIBRARY
// ═══════════════════════════════════════════
const BOOKS=[{cat:"THE HEALTH FRAMEWORK",items:[{img:"https://i.imgur.com/i1DT8Sg.jpg",title:"Everything Came Back Normal",price:"$0.99",amz:"https://www.amazon.com/dp/B0GGXFF66F"},{img:"https://i.imgur.com/3gEZDt9.jpg",title:"Why You Feel Worse When Life Gets Better",price:"$0.99",amz:"https://www.amazon.com/dp/B0FPDF7B3Y"},{img:"https://i.imgur.com/hc5r1Z6.jpg",title:"The Code That Runs Your Life",price:"$0.99",amz:"https://www.amazon.com/dp/B0FR3K5QMW"},{img:"https://i.imgur.com/9sRfgz9.jpg",title:"The Frequency Thief",price:"$0.99",amz:"https://www.amazon.com/dp/B0CXZDCD8D"}]},{cat:"THE BODY & TRAUMA",items:[{img:"https://i.imgur.com/81XxfkH.jpg",title:"My Body Doesn't Feel Like Mine",price:"$0.99",amz:"https://www.amazon.com/dp/B0DKM3GJRT"},{img:"https://i.imgur.com/Y5Zrwc6.jpg",title:"The Cords of the Wicked",price:"$2.99",amz:"https://www.amazon.com/dp/B0GNNNCTP4"},{img:"https://i.imgur.com/7C6Qeya.jpg",title:"Kill The Loop",price:"$0.99",amz:"https://www.amazon.com/dp/B0GHQZHQCZ"}]},{cat:"THE SOVEREIGN LIFE",items:[{img:"https://i.imgur.com/vRXKhjW.jpg",title:"The Covenant Frequency",price:"$2.99",amz:"https://www.amazon.com/dp/B0G27LYZ9Z"},{img:"https://i.imgur.com/2OYSDo9.jpg",title:"Wealth Identity",price:"$0.99",amz:"https://www.amazon.com/dp/B0GD96PBJ6"},{img:"https://i.imgur.com/hbWRKg7.jpg",title:"The Kingley Method",price:"$0.99",amz:"https://www.amazon.com/dp/B0FQ9KXFV5"},{img:"https://i.imgur.com/6hQZUOw.jpg",title:"Sleep Riches",price:"$0.99",amz:"https://www.amazon.com/dp/B0FBS7MZBW"},{img:"https://i.imgur.com/Kh0tJya.jpg",title:"Do THIS",price:"$0.99",amz:"https://www.amazon.com/dp/B0G7YGRXPX"}]},{cat:"THE DIVINE PAIRING",items:[{img:"https://i.imgur.com/z1c8BHf.jpg",title:"Syzygy",price:"$0.99",amz:"https://www.amazon.com/dp/B0F18ZL4DT"}]}];
const Library=({sp})=>(<><Sec pad="8rem 0 3rem"><SL>The Library</SL><Hd sz="clamp(2.2rem,4.5vw,3.2rem)">The Complete Works</Hd><Bd>Each book is a door into the framework. Every door leads to the same room.</Bd><Bd>These are not long reads. Every title is short, focused, and built around a single breakthrough — one concept, one shift, one correction. Most can be read in a single sitting. They are precision instruments, not textbooks. You read one, something clicks, and you move differently from that point forward.</Bd></Sec><Sec>{BOOKS.map(({cat,items})=>(<div key={cat}><p style={{fontFamily:"var(--accent)",fontSize:"1rem",fontWeight:600,letterSpacing:".22em",textTransform:"uppercase",color:"var(--gold-d)",marginBottom:"1.5rem"}}>── {cat} ──</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(175px,1fr))",gap:"1rem",marginBottom:"3rem"}}>{items.map(b=><BC key={b.title} {...b}/>)}</div></div>))}</Sec><section style={{padding:"3rem 1.5rem",textAlign:"center",borderTop:"1px solid rgba(201,168,76,.08)"}}><p style={{fontFamily:"var(--serif)",fontSize:"1.25rem",fontStyle:"italic",color:"var(--cream-m)",marginBottom:"1.5rem"}}>Every book leads to the same door.</p><Btn large onClick={()=>sp(PG.BOOK)}>Book Your Free 15-Minute Session</Btn></section></>);

// ═══════════════════════════════════════════
// FOUNDATION
// ═══════════════════════════════════════════
const Foundation=({sp})=>(<><Sec pad="8rem 0 4rem"><div style={{textAlign:"center"}}><Hd sz="clamp(2.2rem,4.5vw,3.4rem)">Kingley Foundation</Hd><p style={{fontFamily:"var(--accent)",fontSize:"1.15rem",color:"var(--gold-d)",letterSpacing:".1em",marginBottom:"2rem"}}>508(c)(1)(A) Free Church — State of Washington</p><Bd c>The Church is not a building. The Church is the Structure of Divine Love — a living body of sovereigns committed to the systematic correction of thought for the purpose of producing tangible demonstrations of freedom, health, and wholeness.</Bd></div></Sec>
<Sec bg="var(--bg2)"><SL>The Three Pillars</SL><style>{`@media(max-width:768px){.kf-pillars{grid-template-columns:1fr!important}.kf-social{grid-template-columns:1fr!important}}`}</style><div className="kf-pillars" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"1px",background:"rgba(201,168,76,.08)"}}>{[["MAP","We chart the conflicts.","German New Medicine diagnostic framework."],["CORRECT","We correct the thinking.","Rawson's methods. Eddy's discovery."],["COVER","We activate the Covenant.","God's Law. Permanent coverage."]].map(([t,s,d])=>(<div key={t} style={{background:"var(--bg)",padding:"2.5rem 1.5rem",textAlign:"center"}}><div style={{fontFamily:"var(--accent)",fontSize:".95rem",fontWeight:600,letterSpacing:".3em",color:"var(--gold)",marginBottom:"1rem"}}>{t}</div><h3 style={{fontFamily:"var(--serif)",fontSize:"1.2rem",fontWeight:700,color:"var(--cream)",marginBottom:".8rem"}}>{s}</h3><p style={{fontFamily:"var(--accent)",fontSize:"1.05rem",color:"var(--dim)",lineHeight:1.6}}>{d}</p></div>))}</div></Sec>

{/* OPERATOR SCHOOL — PRIVATE */}
<Sec><SL>Spiritual Special Warfare Operator School</SL><Hd sz="clamp(1.6rem,3vw,2.2rem)">Private Membership — By Invitation Only</Hd><Bd>The Operator School is the Kingley Foundation's proprietary training ground — where members learn to identify and correct thinking errors using Rawson's methods, Eddy's original first-edition work, the Five Mechanical Laws from the Codex, and the She-Wolf AI platform. In real time. Under pressure. When the Grid is screaming.</Bd><Bd>This is not a public offering. Our proprietary methods are reserved exclusively for accepted members.</Bd><div style={{margin:"2.5rem auto",maxWidth:600,textAlign:"center"}}><img src="https://i.imgur.com/ktGsAVB.jpg" alt="Operator School Hub" style={{width:"100%",border:"1px solid rgba(201,168,76,.12)",marginBottom:".8rem"}}/><p style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)"}}>The Operator School — Members-Only Hub</p></div><div style={{maxWidth:520,margin:"2rem auto",padding:"2rem",background:"rgba(201,168,76,.03)",border:"1px solid rgba(201,168,76,.1)"}}><h3 style={{fontFamily:"var(--serif)",fontSize:"1.2rem",fontWeight:700,color:"var(--cream)",marginBottom:"1.2rem",textAlign:"center"}}>How to Be Accepted</h3><FI t="Complete a free 15-minute consultation with Malcolm"/><FI t="Receive a personal invitation to membership"/><FI t="Review and agree to the membership agreement"/><FI t="Membership is a paid commitment — not a free offering"/></div><div style={{textAlign:"center",marginTop:"2rem"}}><Btn large onClick={()=>sp(PG.BOOK)}>Book Your 15-Minute Consultation</Btn></div></Sec>

{/* PUBLIC MINISTRY */}
<Sec bg="var(--bg2)"><SL>Free Public Ministry</SL><Hd sz="clamp(1.6rem,3vw,2.2rem)">Malcolm's Free Teaching</Hd><Bd>While the Operator School and proprietary methods are private, Malcolm maintains a free public ministry through YouTube, Instagram, and X. Sermons, teachings, live sessions, and conversations about the framework — available to everyone, always free.</Bd><div className="kf-social" style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:"1rem",marginTop:"2rem"}}>{[["YouTube","@kingley-malcolm","https://www.youtube.com/@kingley-malcolm","🎬"],["Instagram","@malcolmkingley","https://www.instagram.com/malcolmkingley/","📸"],["X (Twitter)","@DNAEVOLVE","https://x.com/DNAEVOLVE","𝕏"]].map(([platform,handle,url,icon])=>(<a key={platform} href={url} target="_blank" rel="noopener noreferrer" style={{display:"block",padding:"2rem 1.5rem",background:"var(--bg)",border:"1px solid rgba(201,168,76,.08)",textAlign:"center",textDecoration:"none",transition:"border-color .3s"}} onMouseEnter={e=>e.currentTarget.style.borderColor="rgba(201,168,76,.3)"} onMouseLeave={e=>e.currentTarget.style.borderColor="rgba(201,168,76,.08)"}><div style={{fontSize:"2rem",marginBottom:".8rem"}}>{icon}</div><div style={{fontFamily:"var(--serif)",fontSize:"1.15rem",fontWeight:700,color:"var(--cream)",marginBottom:".3rem"}}>{platform}</div><div style={{fontFamily:"var(--accent)",fontSize:"1.05rem",color:"var(--gold-d)"}}>{handle}</div></a>))}</div></Sec>

<Sec><SL>Community</SL><Bridge/><TR cols={2} items={[{id:"1181878262",h:"2131f58a37",name:"Peter"},{id:"1181878896",h:"9cbe1dbba2",name:"Julia"},{id:"1181876807",h:"c4e77935e3",name:"Merik"},{id:"1181873843",h:"0a24288a74",name:"Nicole"}]}/></Sec>
<Sec bg="var(--bg2)"><SL>The Signal — Podcast</SL><Hd sz="clamp(1.6rem,3vw,2.2rem)">Go Deeper</Hd><Bd>Long-form teachings on the She-Wolf, the framework, the Covenant, and sovereign life. Exclusive to this site — not available on any other platform.</Bd>
{[{title:"Must Listen! She-Wolf Changes Your Identity!",sub:"That's The Secret to Permanent Wealth, Love, and Wellbeing.",src:"https://healswitch.s3.us-east-2.amazonaws.com/CTA+MASTERY+AUDIO.mp3",featured:true},{title:"The Code That Runs Your Life",sub:"How I Built The She-Wolf.",src:"https://healswitch.s3.us-east-2.amazonaws.com/thecode.mp3"},{title:"Ep 01 — The Kingley Method",sub:"How to Dissolve All Negativity in 10-Seconds. You are about to take admin keys to reality.",src:"https://healswitch.s3.amazonaws.com/The%20Kingley%20Method.mp3"},{title:"Ep 02 — Sleep Riches",sub:"The Backdoor Key to Limitless Abundance. Unlock Wealth While You Sleep.",src:"https://healswitch.s3.us-east-2.amazonaws.com/Sleep+Riches.mp3"},{title:"Ep 03 — There Is Nothing Wrong!",sub:"I Will Prove It. Exposing The Patterns Will Change Your Destiny.",src:"https://healswitch.s3.us-east-2.amazonaws.com/There+Is+Nothing+Wrong+With+You.mp3"},{title:"Wealth Identity",sub:"Change Your Position, Your Possessions Follow. The Real Secret is WHO You're Being.",src:"https://healswitch.s3.us-east-2.amazonaws.com/wealth+identity.mp3"}].map(({title,sub,src,featured},i)=>(<div key={i} style={{background:featured?"rgba(201,168,76,.06)":"var(--bg)",border:featured?"1px solid rgba(201,168,76,.2)":"1px solid rgba(201,168,76,.06)",padding:"1.5rem 2rem",marginBottom:".8rem"}}>{featured&&<div style={{fontFamily:"var(--accent)",fontSize:".85rem",fontWeight:600,letterSpacing:".2em",textTransform:"uppercase",color:"var(--gold)",marginBottom:".8rem"}}>★ FEATURED EPISODE</div>}<h4 style={{fontFamily:"var(--serif)",fontSize:"1.15rem",fontWeight:700,color:"var(--cream)",marginBottom:".4rem"}}>{title}</h4><p style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",marginBottom:"1rem",lineHeight:1.5}}>{sub}</p><audio controls preload="none" style={{width:"100%",height:42,filter:"sepia(20%) saturate(70%) brightness(90%) hue-rotate(5deg)"}} src={src}/></div>))}
</Sec>
<Sec><div style={{textAlign:"center"}}><SL>Support the Mission</SL><Bd c>Your tithes, offerings, and faith seeds sustain this work.</Bd><Btn large onClick={()=>sp(PG.GIVE)}>GIVE</Btn><p style={{marginTop:"1rem",fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)"}}>508(c)(1)(A). Contributions received under ecclesiastical authority.</p></div></Sec></>);

// ═══════════════════════════════════════════
// GIVE PAGE — Full giving flow integrated
// ═══════════════════════════════════════════
const PAY={PAYPAL:"https://www.paypal.com/donate/?hosted_button_id=REL4NASVXB7N8",STRIPE:"https://buy.stripe.com/fZu4gyfLodtubUBfxt1Nu0s",CASHAPP:"https://cash.app/$MinisterofAllowing"};
const CRYPTO={BTC:"bc1qmp9nlcz8v08daw5pkyxw9m4sv9ngpcay5ez9vm",XRP:"rpTyKsuDFi3fwirZbtE2hx2pGZujdjCvvD",ETH:"0x01471a6d0AF741A87172961c599a06bA2f0fDB09"};

const CryptoRow=({label,addr})=>{const[cp,setCp]=useState(false);return(<div style={{padding:"1.2rem 1.5rem",background:"rgba(201,168,76,.03)",border:"1px solid rgba(201,168,76,.08)",marginBottom:".8rem"}}><div style={{fontFamily:"var(--serif)",fontSize:"1.1rem",fontWeight:700,color:"var(--cream)",marginBottom:".6rem"}}>{label}</div><div style={{display:"flex",alignItems:"center",gap:".8rem",background:"var(--bg)",padding:".8rem 1rem",border:"1px solid rgba(201,168,76,.06)"}}><span style={{fontFamily:"monospace",fontSize:".85rem",color:"var(--muted)",wordBreak:"break-all",flex:1}}>{addr}</span><button onClick={()=>{navigator.clipboard.writeText(addr);setCp(true);setTimeout(()=>setCp(false),2000)}} style={{fontFamily:"var(--accent)",fontSize:".9rem",color:cp?"#4ade80":"var(--gold-d)",background:"none",border:"1px solid rgba(201,168,76,.15)",padding:".4rem .8rem",cursor:"pointer"}}>{cp?"Copied":"Copy"}</button></div></div>)};

const GivePage=({sp})=>{
  const[screen,setScreen]=useState("welcome");
  const[desire,setDesire]=useState("");
  const[med,setMed]=useState(null);
  const[loading,setLoading]=useState(false);

  const generateMed=async()=>{
    setLoading(true);
    try{
      const gemini=new GoogleGenAI({apiKey:import.meta.env.VITE_GEMINI_API_KEY});
      const prompt=`You are a spiritual guide operating in the tradition of Frederick L. Rawson and Biblical covenant law. A person is planting a faith seed and believing God for: "${desire}". Write a response in JSON with these fields: {"meditation":"A 150-word meditation on the spiritual reality of their desire already being fulfilled in Spirit, using Rawson's framework that the spiritual idea has not a single element of error. Reference one specific scripture (NKJV).","lawTitle":"Name of one specific Biblical law or principle that applies","law":"A 100-word explanation of how this law operates mechanically to produce the harvest they are believing for.","rephrasedDesire":"Their desire rephrased in the present tense as already received, in elegant language","multiplier":"hundredfold"} Return ONLY the JSON, no markdown.`;
      const result=await gemini.models.generateContent({model:"gemini-2.5-flash",contents:[{role:"user",parts:[{text:prompt}]}]});
      const t=result.text||"";
      const clean=t.replace(/```json|```/g,"").trim();
      setMed(JSON.parse(clean));
      setScreen("meditation");
    }catch(e){console.error(e);setMed({meditation:"The spiritual reality of your desire is already complete in the Mind of God. What you are believing for has never been absent — it has been waiting for the vessel of your faith to receive it. 'Before they call, I will answer; and while they are still speaking, I will hear.' (Isaiah 65:24 NKJV). The material appearance of lack is the counterfeit. The spiritual fact is wholeness. Rest in this knowing.",lawTitle:"The Law of Sowing and Reaping",law:"'He who sows sparingly will also reap sparingly, and he who sows bountifully will also reap bountifully.' (2 Corinthians 9:6). This is mechanical law — as reliable as gravity. The seed you plant in faith, with cheerfulness, enters the Covenant's operating system and returns multiplied.",rephrasedDesire:desire,multiplier:"hundredfold"});setScreen("meditation")}
    finally{setLoading(false)}
  };

  // WELCOME
  if(screen==="welcome")return(<div style={{maxWidth:820,margin:"0 auto",padding:"7rem 1.5rem 3rem"}}><div style={{textAlign:"center"}} className="fade-in d1"><Hd sz="clamp(2rem,4vw,3rem)">Tithes, Offerings <em style={{color:"var(--gold)",fontStyle:"italic"}}>&amp; Faith Seeds</em></Hd><p style={{fontFamily:"var(--accent)",fontSize:"1.15rem",color:"var(--muted)",marginBottom:"2rem"}}>"You Can't Outgive God."</p></div>
  <div className="fade-in d2" style={{border:"1px solid rgba(201,168,76,.15)",background:"#000",marginBottom:"1.5rem",position:"relative",width:"100%",paddingBottom:"56.25%"}}><video src="https://healswitch.s3.us-east-2.amazonaws.com/the_biblical_laws_of_financial_increase_v1+(1080p).mp4" poster="https://i.imgur.com/JCJktZf.jpg" controls playsInline style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",objectFit:"contain"}}/></div>
  <div style={{textAlign:"center",marginBottom:"2.5rem"}}><Btn large onClick={()=>setScreen("payment")}>Give Now</Btn><p style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",marginTop:".8rem"}}>PayPal · Stripe · CashApp · BTC · ETH · XRP</p></div>
  <div style={{textAlign:"center",marginBottom:"2.5rem"}}><button onClick={()=>setScreen("harvest")} style={{fontFamily:"var(--accent)",fontSize:"1.1rem",color:"var(--gold-d)",background:"none",border:"2px solid var(--gold-d)",padding:".9rem 2.5rem",cursor:"pointer",letterSpacing:".1em",transition:"all .3s"}} onMouseEnter={e=>{e.target.style.background="var(--gold-d)";e.target.style.color="var(--bg)"}} onMouseLeave={e=>{e.target.style.background="none";e.target.style.color="var(--gold-d)"}}>Prepare My Heart to Receive My Good</button></div>
  <div style={{padding:"2rem",background:"rgba(201,168,76,.03)",border:"1px solid rgba(201,168,76,.08)"}}><p style={{fontFamily:"var(--serif)",fontSize:"1.15rem",fontStyle:"italic",color:"var(--cream-m)",lineHeight:1.6}}>"Bring all the tithes into the storehouse, that there may be food in My house, and try Me now in this," says the LORD of hosts, "If I will not open for you the windows of heaven and pour out for you such blessing that there will not be room enough to receive it."</p><p style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--gold-d)",textAlign:"right",marginTop:"1rem"}}>— Malachi 3:10 NKJV</p></div>
  <div style={{marginTop:"2.5rem",textAlign:"center"}}><img src="https://i.imgur.com/vRXKhjW.jpg" alt="Covenant Frequency" style={{width:"100%",maxWidth:260,border:"1px solid rgba(201,168,76,.12)",marginBottom:"1.5rem"}}/><h3 style={{fontFamily:"var(--serif)",fontSize:"1.3rem",fontWeight:700,color:"var(--cream)",marginBottom:".6rem"}}>Free Gift: The Covenant Frequency</h3><p style={{fontFamily:"var(--accent)",fontSize:"1.05rem",color:"var(--muted)",marginBottom:"1.2rem"}}>The sovereign's manual for activating the ancient laws.</p><Btn href="https://drive.google.com/file/d/1BTl3Wlp3EPrB-hoOjXK1Ollt0yNCCaYs/view?usp=sharing">Download Free</Btn></div>
  </div>);

  // HARVEST
  if(screen==="harvest")return(<div style={{maxWidth:600,margin:"0 auto",padding:"7rem 1.5rem 3rem",textAlign:"center"}} className="fade-in d1"><Hd>Declare Your Harvest</Hd><Bd c>What are you using your faith to believe God for? Be specific. Write it down and make it plain.</Bd><textarea value={desire} onChange={e=>setDesire(e.target.value)} placeholder="e.g., 'Perfect health in my body,' 'Financial abundance to clear all debts,' 'Wisdom to lead my family'..." style={{width:"100%",minHeight:160,padding:"1.2rem",background:"var(--bg)",border:"1px solid rgba(201,168,76,.15)",color:"var(--cream)",fontFamily:"var(--accent)",fontSize:"1.1rem",outline:"none",resize:"vertical",lineHeight:1.6,marginBottom:"1.5rem"}}/><Btn large onClick={generateMed}>Submit</Btn><div style={{marginTop:"1.5rem"}}><button onClick={()=>setScreen("welcome")} style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",background:"none",border:"none",cursor:"pointer"}}>← Back</button></div></div>);

  // LOADING
  if(loading)return(<div style={{maxWidth:600,margin:"0 auto",padding:"12rem 1.5rem",textAlign:"center"}}><div style={{width:50,height:50,border:"3px solid rgba(201,168,76,.2)",borderTop:"3px solid var(--gold)",borderRadius:"50%",animation:"spin 1s linear infinite",margin:"0 auto 1.5rem"}}></div><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style><p style={{fontFamily:"var(--accent)",fontSize:"1.15rem",color:"var(--muted)"}}>Preparing your meditation...</p></div>);

  // MEDITATION
  if(screen==="meditation"&&med)return(<div style={{maxWidth:700,margin:"0 auto",padding:"7rem 1.5rem 3rem"}} className="fade-in d1"><div style={{textAlign:"center",marginBottom:"2rem"}}><Hd>A Word of Gnosis</Hd></div><div style={{marginBottom:"2rem"}}><h3 style={{fontFamily:"var(--serif)",fontSize:"1.2rem",color:"var(--gold-l)",marginBottom:"1rem",borderBottom:"1px solid rgba(201,168,76,.1)",paddingBottom:".8rem"}}>Meditation on Reality</h3><p style={{fontSize:"1.15rem",color:"var(--cream-m)",lineHeight:1.7,whiteSpace:"pre-wrap"}}>{med.meditation}</p></div><div style={{marginBottom:"2rem"}}><h3 style={{fontFamily:"var(--serif)",fontSize:"1.2rem",color:"var(--gold-l)",marginBottom:"1rem",borderBottom:"1px solid rgba(201,168,76,.1)",paddingBottom:".8rem"}}>{med.lawTitle}</h3><p style={{fontSize:"1.15rem",color:"var(--cream-m)",lineHeight:1.7,whiteSpace:"pre-wrap"}}>{med.law}</p></div><div style={{textAlign:"center"}}><Btn large onClick={()=>setScreen("declaration")}>Prepare My Declaration</Btn><div style={{marginTop:"1rem"}}><button onClick={()=>setScreen("payment")} style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",background:"none",border:"none",cursor:"pointer"}}>Skip to giving →</button></div><div style={{marginTop:".5rem"}}><button onClick={()=>setScreen("meditation")||setScreen("harvest")} style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",background:"none",border:"none",cursor:"pointer"}}>← Back</button></div></div></div>);

  // DECLARATION
  if(screen==="declaration"&&med)return(<div style={{maxWidth:700,margin:"0 auto",padding:"7rem 1.5rem 3rem",textAlign:"center"}} className="fade-in d1"><Hd>Speak Your Faith</Hd><Bd c>Read this declaration aloud. Let the words resonate from your spirit.</Bd><div style={{padding:"2.5rem",background:"rgba(201,168,76,.03)",border:"1px solid rgba(201,168,76,.12)",textAlign:"left",marginBottom:"2rem"}}><p style={{fontFamily:"var(--serif)",fontSize:"1.25rem",fontStyle:"italic",color:"var(--cream)",lineHeight:1.7}}>"I believe that I have already received <strong style={{color:"var(--gold)",fontStyle:"normal"}}>{med.rephrasedDesire}</strong>. Out of the overflow of abundance in Me, I plant this seed with faith and birth supernatural expectation within. I am resting on Divine Law now. I release this money freely and God returns it to me exceedingly — multiplied a <strong style={{color:"var(--gold)",fontStyle:"normal"}}>{med.multiplier}</strong>, in Jesus Christ's name. It is done."</p></div><Bd c>Your heart is now ready to sow your faith-seed.</Bd><Btn large onClick={()=>setScreen("payment")}>Proceed to Give</Btn><div style={{marginTop:"1rem"}}><button onClick={()=>setScreen("meditation")} style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",background:"none",border:"none",cursor:"pointer"}}>← Back</button></div></div>);

  // PAYMENT
  if(screen==="payment")return(<div style={{maxWidth:600,margin:"0 auto",padding:"7rem 1.5rem 3rem"}} className="fade-in d1"><div style={{textAlign:"center",marginBottom:"2rem"}}><Hd>Choose Your Method</Hd><p style={{fontFamily:"var(--accent)",fontSize:"1.1rem",color:"var(--muted)",fontStyle:"italic"}}>"You Can't Outgive God."</p></div>{[["PayPal",PAY.PAYPAL],["Stripe — Credit/Debit, Klarna",PAY.STRIPE],["Cash App",PAY.CASHAPP]].map(([l,u])=>(<a key={l} href={u} target="_blank" rel="noopener noreferrer" style={{display:"flex",alignItems:"center",padding:"1.2rem 1.5rem",background:"rgba(201,168,76,.03)",border:"1px solid rgba(201,168,76,.08)",marginBottom:".8rem",textDecoration:"none",transition:"background .3s"}} onMouseEnter={e=>e.currentTarget.style.background="rgba(201,168,76,.08)"} onMouseLeave={e=>e.currentTarget.style.background="rgba(201,168,76,.03)"}><span style={{fontFamily:"var(--serif)",fontSize:"1.15rem",fontWeight:700,color:"var(--cream)"}}>{l}</span><span style={{marginLeft:"auto",fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--gold-d)"}}>→</span></a>))}<div style={{borderTop:"1px solid rgba(201,168,76,.1)",margin:"1.5rem 0",paddingTop:"1.5rem"}}><p style={{fontFamily:"var(--accent)",fontSize:"1rem",fontWeight:600,color:"var(--gold-d)",letterSpacing:".15em",marginBottom:"1rem"}}>CRYPTOCURRENCY</p><CryptoRow label="Bitcoin (BTC)" addr={CRYPTO.BTC}/><CryptoRow label="Ethereum (ETH) & Stablecoins" addr={CRYPTO.ETH}/><CryptoRow label="XRP" addr={CRYPTO.XRP}/></div><div style={{marginTop:"2rem",textAlign:"center"}}><button onClick={()=>setScreen("welcome")} style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",background:"none",border:"none",cursor:"pointer"}}>← Back</button></div>
  <div style={{marginTop:"2.5rem",padding:"1.5rem",background:"var(--bg2)",border:"1px solid rgba(201,168,76,.06)"}}><details><summary style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--cream-m)",cursor:"pointer"}}>Important Disclaimers</summary><div style={{marginTop:"1rem",fontFamily:"var(--accent)",fontSize:".95rem",color:"var(--dim)",lineHeight:1.6}}><p style={{marginBottom:".8rem"}}>All materials presented on MalcolmKingley.Org are offered for spiritual exploration by the Kingley Foundation, a 508(c)(1)(a) organization. Nothing herein constitutes medical, legal, financial, or professional advice.</p><p style={{marginBottom:".8rem"}}>Participation is voluntary. Donations are gifts of support to our private spiritual ministry. They do not constitute purchase of services nor create any guarantee of outcome.</p><p>By engaging with this site or making a donation, you acknowledge that all content exists within the realm of spiritual belief and you accept full responsibility for your own choices.</p></div></details></div></div>);

  return null;
};

// ═══════════════════════════════════════════
// LEGAL PAGES
// ═══════════════════════════════════════════
const LP=({title,children})=>(<div style={{maxWidth:820,margin:"0 auto",padding:"7rem 1.5rem 4rem"}}><SL>Legal</SL><Hd sz="clamp(1.8rem,3.5vw,2.6rem)">{title}</Hd><p style={{fontFamily:"var(--accent)",fontSize:"1rem",color:"var(--dim)",marginBottom:"3rem"}}>Kingley Foundation — 508(c)(1)(A) — State of Washington — Last updated: April 2026</p><div style={{fontFamily:"var(--accent)",fontSize:"1.15rem",color:"var(--cream-m)",lineHeight:1.7}}>{children}</div></div>);
const LH=({children})=>(<h3 style={{fontFamily:"var(--serif)",fontSize:"1.3rem",fontWeight:700,color:"var(--cream)",marginTop:"2.5rem",marginBottom:"1rem"}}>{children}</h3>);
const LB=({children})=>(<p style={{marginBottom:"1.2rem"}}>{children}</p>);

const Privacy=()=>(<LP title="Privacy Policy">
<LB>The Kingley Foundation ("we," "us," "our") operates MalcolmKingley.org. This Privacy Policy describes how we collect, use, store, and protect your personal information when you visit our website, register for training, book sessions, make donations, or interact with our services.</LB>
<LH>Information We Collect</LH>
<LB><strong style={{color:"var(--cream)"}}>Information you provide directly:</strong> When you register for our free training, book a session, or make a donation, we may collect your name, email address, phone number, and payment information. Payment information is processed by third-party processors (PayPal, Stripe, Cash App) and is never stored on our servers.</LB>
<LB><strong style={{color:"var(--cream)"}}>Information collected automatically:</strong> We may collect your IP address, browser type, device type, operating system, referring URLs, pages visited, and time spent on pages through standard web analytics tools (such as Google Analytics and Meta Pixel) for the purpose of understanding site usage and improving our services.</LB>
<LB><strong style={{color:"var(--cream)"}}>Cookies and tracking technologies:</strong> We use cookies, pixels, and similar technologies to analyze traffic, personalize content, and serve relevant advertisements. You may disable cookies in your browser settings, though some site functionality may be affected.</LB>
<LH>How We Use Your Information</LH>
<LB>We use your information to: deliver the training, books, and session services you have requested; communicate with you about your session, our services, and related spiritual content; process your donations through third-party payment processors; send you email communications (which you may opt out of at any time); improve our website and services; comply with legal obligations.</LB>
<LH>Email Communications</LH>
<LB>When you register for our training, you consent to receive email communications from the Kingley Foundation. These may include follow-up content, session reminders, new book announcements, and ministry updates. Every email includes an unsubscribe link. You may opt out at any time by clicking that link or emailing us directly. We use Brevo (formerly Sendinblue) as our email service provider. Your contact information is stored on their servers subject to their privacy policy.</LB>
<LH>Third-Party Services</LH>
<LB>We use the following third-party services that may collect or process your data: Brevo (email marketing), Vimeo (video hosting), Google Analytics (site analytics), Meta Pixel (advertising analytics), Calendly (session scheduling), PayPal, Stripe, and Cash App (payment processing), Amazon (book sales). Each of these services operates under its own privacy policy. We encourage you to review them.</LB>
<LH>Cryptocurrency Donations</LH>
<LB>If you make a donation via cryptocurrency (Bitcoin, Ethereum, XRP), the transaction is recorded on the public blockchain. We store the transaction record for our internal accounting. Cryptocurrency transactions are irreversible by nature.</LB>
<LH>Data Retention</LH>
<LB>We retain your personal information for as long as necessary to provide our services and fulfill the purposes described in this policy. You may request deletion of your data at any time by contacting us. We will comply within 30 days, except where we are required by law to retain certain records.</LB>
<LH>Data Security</LH>
<LB>We implement reasonable administrative, technical, and physical safeguards to protect your personal information. However, no method of transmission over the Internet or electronic storage is 100% secure. We cannot guarantee absolute security.</LB>
<LH>Children's Privacy</LH>
<LB>Our services are not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware that we have collected information from a child, we will take steps to delete it promptly.</LB>
<LH>Your Rights</LH>
<LB>Depending on your jurisdiction, you may have the right to: access the personal information we hold about you; request correction of inaccurate information; request deletion of your information; opt out of marketing communications; request a copy of your data in a portable format. To exercise any of these rights, contact us at the address below.</LB>
<LH>California Residents (CCPA)</LH>
<LB>If you are a California resident, you have the right to know what personal information we collect, request deletion, and opt out of the sale of personal information. We do not sell personal information. To make a request, contact us using the information below.</LB>
<LH>Changes to This Policy</LH>
<LB>We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated effective date. Your continued use of the site after changes constitutes acceptance of the updated policy.</LB>
<LH>Contact</LH>
<LB>Kingley Foundation — 508(c)(1)(A) Ecclesiastical Organization — State of Washington<br/>Email: contact@malcolmkingley.org<br/>Website: MalcolmKingley.org</LB>
</LP>);

const Terms=()=>(<LP title="Terms & Conditions">
<LB>By accessing and using MalcolmKingley.org ("the Site"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, do not use the Site.</LB>
<LH>Nature of Services</LH>
<LB>The Kingley Foundation is a 508(c)(1)(A) free-church ecclesiastical organization registered in the State of Washington. All content, services, training, sessions, books, applications, and programs offered through this Site are provided for spiritual, educational, and ecclesiastical purposes only. They are protected expressions of sincerely held religious belief under the First Amendment to the United States Constitution.</LB>
<LH>No Professional Advice</LH>
<LB>Nothing on this Site constitutes medical advice, mental health counseling, psychiatric treatment, psychological therapy, financial advice, legal advice, or any form of licensed professional service. The frameworks referenced (including German New Medicine, the work of Frederick L. Rawson, and Biblical covenant principles) are presented as conceptual and spiritual models, not as scientifically validated medical protocols.</LB>
<LB>If you are experiencing physical symptoms, mental health challenges, financial difficulties, or any other professional concern, you are strongly encouraged to consult a qualified, licensed professional in addition to any spiritual practice you may choose to engage in.</LB>
<LH>Personal Responsibility</LH>
<LB>You assume full responsibility for any actions taken based on the content of this Site. The Kingley Foundation, Malcolm Kingley, and all associated parties shall not be held liable for any damages, losses, or consequences arising from the use or application of any information, framework, technology, or practice described on this Site or in any associated publication, session, or program.</LB>
<LH>Donations and Giving</LH>
<LB>All donations made through the Site — whether tithes, offerings, faith seeds, or alms — are voluntary gifts of support to the Kingley Foundation's private spiritual ministry. Donations do not constitute the purchase of goods or services. No donation creates a guarantee, warranty, or promise of any specific outcome — financial, spiritual, physical, or otherwise.</LB>
<LB>Donations are received under the ecclesiastical authority of the Kingley Foundation as a 508(c)(1)(A) organization. Donors are responsible for understanding the tax implications of their contributions in their jurisdiction.</LB>
<LB>Donations made via cryptocurrency are irreversible. Donations made via PayPal, Stripe, or Cash App are subject to those platforms' respective refund policies. The Kingley Foundation processes refund requests on a case-by-case basis at its sole discretion.</LB>
<LH>Intellectual Property</LH>
<LB>All content on this Site — including text, images, videos, books, training materials, the She-Wolf platform, the Operator School curriculum, and the Architect's Codex — is the intellectual property of Malcolm Kingley and/or the Kingley Foundation. No content may be reproduced, distributed, or transmitted in any form without prior written permission, except for brief quotations in reviews and certain noncommercial uses permitted by copyright law.</LB>
<LH>User Conduct</LH>
<LB>You agree not to: use the Site for any unlawful purpose; attempt to gain unauthorized access to any part of the Site; reproduce, distribute, or commercially exploit any content without permission; impersonate any person or entity; harass, abuse, or harm any other user or individual.</LB>
<LH>Session Services</LH>
<LB>Free 15-minute sessions with Malcolm Kingley are offered at the sole discretion of the Kingley Foundation. Availability is limited. Sessions are spiritual consultations, not medical appointments, therapy sessions, or professional advisory services. No therapeutic or clinical relationship is created by participating in a session.</LB>
<LH>AI-Powered Features</LH>
<LB>Certain features of the Site (including the She-Wolf platform and the meditation generation feature on the giving page) utilize artificial intelligence. AI-generated content is provided for spiritual reflection and is not a substitute for professional advice. The Kingley Foundation does not guarantee the accuracy, completeness, or appropriateness of any AI-generated content.</LB>
<LH>Third-Party Links</LH>
<LB>The Site may contain links to third-party websites (including Amazon, payment processors, and social media platforms). We are not responsible for the content, privacy practices, or terms of service of any third-party site.</LB>
<LH>Limitation of Liability</LH>
<LB>To the maximum extent permitted by law, the Kingley Foundation, Malcolm Kingley, and all associated parties shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Site, your participation in any session or program, your reliance on any content, or your donations. Our total liability shall not exceed the amount you have donated in the preceding twelve months.</LB>
<LH>Indemnification</LH>
<LB>You agree to indemnify and hold harmless the Kingley Foundation, Malcolm Kingley, and all associated parties from any claims, damages, losses, or expenses (including legal fees) arising from your use of the Site, your violation of these Terms, or your violation of any third party's rights.</LB>
<LH>Governing Law</LH>
<LB>These Terms shall be governed by the laws of the State of Washington, without regard to conflict of law principles. Any disputes shall be resolved in the courts of the State of Washington.</LB>
<LH>Severability</LH>
<LB>If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.</LB>
<LH>Changes</LH>
<LB>We reserve the right to modify these Terms at any time. Changes will be posted on this page. Your continued use of the Site constitutes acceptance of the updated Terms.</LB>
<LH>Contact</LH>
<LB>Kingley Foundation — 508(c)(1)(A) Ecclesiastical Organization — State of Washington<br/>Email: contact@malcolmkingley.org<br/>Website: MalcolmKingley.org</LB>
</LP>);

const Disclaimer=()=>(<LP title="Disclaimer">
<LH>General Disclaimer</LH>
<LB>All materials, features, applications, writings, books, training programs, sessions, and technologies presented on MalcolmKingley.org and by the Kingley Foundation are offered strictly for spiritual, educational, and ecclesiastical purposes. They reflect the personal experiences, spiritual convictions, and philosophical framework of Malcolm Kingley and the Kingley Foundation.</LB>
<LH>Not Medical Advice</LH>
<LB>Nothing on this Site is intended to diagnose, treat, cure, mitigate, or prevent any disease, disorder, or medical condition. No claim is made — express or implied — that any method, framework, technology, or practice described herein can or will produce any specific medical, physiological, or psychological outcome. The German New Medicine framework and the spiritual correction methods referenced are presented as conceptual models for understanding the relationship between emotional experience and biological response. They are not offered as replacements for conventional medical care.</LB>
<LB>If you are experiencing physical symptoms, you are strongly encouraged to consult with a qualified, licensed medical professional. If you are experiencing a mental health crisis, please contact a qualified mental health professional or call 988 (Suicide and Crisis Lifeline) or your local emergency services.</LB>
<LH>Not Financial Advice</LH>
<LB>The principles of biblical giving (tithing, first fruits, faith seeds, alms) described on this Site and in our publications are presented as spiritual practices based on scriptural interpretation. They are not financial advice. No representation is made that any giving practice will produce a specific financial return. You should consult a qualified financial advisor before making financial decisions.</LB>
<LH>Not Legal Advice</LH>
<LB>Nothing on this Site constitutes legal advice. The Kingley Foundation's 508(c)(1)(A) status and the legal frameworks discussed are presented for informational purposes only. Consult a qualified attorney for legal guidance.</LB>
<LH>Not Therapy or Counseling</LH>
<LB>Malcolm Kingley is not a physician, psychiatrist, psychologist, licensed therapist, licensed counselor, or healthcare provider of any kind. Sessions, training, and content provided by Malcolm Kingley and the Kingley Foundation do not constitute therapy, counseling, or any form of licensed mental health treatment. No therapeutic or clinical relationship is created.</LB>
<LH>Personal Testimonials</LH>
<LB>Testimonials and personal accounts shared on this Site reflect the subjective experiences of specific individuals. They are presented as spiritual testimonies, not as evidence of medical efficacy. They are not guarantees that any other individual will achieve similar results. Individual results vary. Some testimonials reference Malcolm Kingley's former legal name, Matthew David Hurtado.</LB>
<LH>AI-Generated Content</LH>
<LB>Certain features of this Site utilize artificial intelligence to generate personalized spiritual reflections, meditations, and declarations. This content is generated algorithmically and is intended for spiritual reflection only. It does not constitute professional advice of any kind. The Kingley Foundation does not guarantee the theological accuracy or appropriateness of AI-generated content.</LB>
<LH>Ecclesiastical Protection</LH>
<LB>The Kingley Foundation is a 508(c)(1)(A) free-church ecclesiastical organization registered in the State of Washington, United States. All content, practices, and services offered by the Foundation are protected expressions of sincerely held religious belief under the First Amendment to the United States Constitution and applicable federal and state law.</LB>
<LH>Assumption of Risk</LH>
<LB>By using this Site, participating in any session, enrolling in any program, reading any publication, or making any donation, you acknowledge that: (1) you are engaging in a voluntary spiritual and educational practice; (2) no professional advisory, therapeutic, or clinical relationship is created; (3) Malcolm Kingley and the Kingley Foundation assume no liability for any decisions you make based on this content; (4) you bear sole responsibility for your own health, wellbeing, financial decisions, and care; and (5) you have read and agree to our Terms & Conditions and Privacy Policy.</LB>
<LH>Sensitive Content Notice</LH>
<LB>Some publications and content offered by the Kingley Foundation address sensitive topics including sexual abuse, trauma, narcissistic abuse, addiction, and chronic illness. This content may be activating for individuals with personal experience in these areas. Please engage at your own pace and in a context where you feel safe. If you are currently in crisis, please contact a qualified professional before engaging with this content.</LB>
<LH>Contact</LH>
<LB>Kingley Foundation — 508(c)(1)(A) Ecclesiastical Organization — State of Washington<br/>Email: contact@malcolmkingley.org<br/>Website: MalcolmKingley.org</LB>
</LP>);

// ── Footer ──
const Foot=({sp})=>(<footer style={{padding:"2.5rem 2rem",textAlign:"center",borderTop:"1px solid rgba(201,168,76,.08)"}}>
<div style={{display:"flex",justifyContent:"center",gap:"2rem",marginBottom:"1.5rem"}}>{[["About",PG.ABOUT],["Library",PG.LIBRARY],["Foundation",PG.FOUNDATION],["Give",PG.GIVE]].map(([l,p])=>(<span key={p} onClick={()=>sp(p)} style={{fontFamily:"var(--accent)",fontSize:"1.05rem",color:"var(--dim)",cursor:"pointer"}}>{l}</span>))}</div>
<div style={{display:"flex",justifyContent:"center",gap:"2rem",marginBottom:"1.5rem",borderTop:"1px solid rgba(201,168,76,.04)",paddingTop:"1rem"}}>{[["Privacy Policy",PG.PRIVACY],["Terms & Conditions",PG.TERMS],["Disclaimer",PG.DISCLAIMER]].map(([l,p])=>(<span key={p} onClick={()=>sp(p)} style={{fontFamily:"var(--accent)",fontSize:".95rem",color:"var(--dim)",cursor:"pointer",textDecoration:"underline",textDecorationColor:"rgba(201,168,76,.15)",textUnderlineOffset:"3px"}}>{l}</span>))}</div>
<p style={{fontFamily:"var(--accent)",fontSize:".95rem",color:"var(--dim)"}}>Kingley Foundation — 508(c)(1)(A) — State of Washington</p><p style={{fontFamily:"var(--accent)",fontSize:".95rem",color:"var(--dim)",marginTop:".3rem"}}>© Malcolm Kingley. All rights reserved.</p></footer>);

// ── App ──
export default function App(){const[pg,setPg]=useState(PG.HOME);const nav=p=>{setPg(p);window.scrollTo({top:0,behavior:"instant"})};return(<div style={{minHeight:"100vh",background:"var(--bg)"}}><GS/><Nav pg={pg} sp={nav}/>{pg===PG.HOME&&<Home sp={nav}/>}{pg===PG.TRAINING&&<Training sp={nav}/>}{pg===PG.WATCH&&<Watch sp={nav}/>}{pg===PG.BOOK&&<Book/>}{pg===PG.ABOUT&&<About sp={nav}/>}{pg===PG.LIBRARY&&<Library sp={nav}/>}{pg===PG.FOUNDATION&&<Foundation sp={nav}/>}{pg===PG.GIVE&&<GivePage sp={nav}/>}{pg===PG.PRIVACY&&<Privacy/>}{pg===PG.TERMS&&<Terms/>}{pg===PG.DISCLAIMER&&<Disclaimer/>}{!FN.includes(pg)&&pg!==PG.GIVE&&<Foot sp={nav}/>}</div>)}
